Mypotifolio/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portifolio.urls', namespace= 'portifolio')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portifolio/urls.py
from django.urls import path
from . import views

# App's urls go here
app_name = 'portifolio'
urlpatterns = [
    path('', views.index, name= 'index'),
    path('about/', views.about, name= 'about'),
    path('services/', views.services, name= 'services'),
    path('portfolio/', views.portfolio, name= 'portfolio'),
    path('contacts/', views.contacts, name= 'contacts'),
]

portifolio/models.py
from django.db import models

# Create your models here.

class PortfolioProject (models.Model):
    title = models.CharField (max_length=100)
    description = models.TextField ()
    image = models.ImageField (upload_to= 'portfoilio_images/', null= True, blank=True)
    technologies_used = models.CharField (max_length=100)
    website_link = models.URLField (null=True, blank=True)

    def __str__(self):
        return self.title

portifolio/views.py
from django.shortcuts import render
from . models import PortfolioProject

# Create your views here.

def index (request):
    return render (request, 'portifolio/index.html')

def about (request):
    return render (request, 'portifolio/about.html')

def services (request):
    return render (request, 'portifolio/services.html')

def portfolio (request):
    projects = PortfolioProject.objects.all()
    return render (request, 'portifolio/potifolio.html', {'projects':projects})

def contacts (request):
    return render (request, 'portifolio/contacts.html')

portifolio/templates/portifolio/about.html
{% extends 'portifolio/base.html' %}
{% load static %}
{% block title %}About me{% endblock %}
{% block content %}

<h1 class="about-header"><b>About me</b></h1>
<div class="about-div">
    <p class="about-texts">
        I am a Bachelor of Science in Environmental Health student in Tanzania and a passionate software developer. My portfolio showcases software development projects that merge technology with environmental health to create impactful solutions.
    </p>
    
    <p class="about-texts">
        Thank you for visiting. I look forward to collaborating on projects that drive positive change.
    </p>
    
</div>
{% endblock %}

portifolio/templates/portifolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'portifolio/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
    crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
    crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <title>{% block title %}Msita's portifolio{% endblock %}</title>
</head>

<body>

    <header>
        <img src="{% static 'portifolio/img/Myprofile.jpg' %}" alt="Msita">
        <h1>Michael Msita</h1>
        <p>Bachelor of Science in Environmental Health | Software Developer | Graphics designer | Based in Tanzania</p>
        <nav>
            <i id="menu-icon" class="fas fa-bars hamburger-icon"></i>
            <ul>
                <li><a href="{% url 'portifolio:index' %}">Home</a></li>
                <li><a href="{% url 'portifolio:about' %}">About Me</a></li>
                <li><a href="{% url 'portifolio:services' %}">Services</a></li>
                <li><a href="{% url 'portifolio:portfolio' %}">Portifolio</a></li>
                <li><a href="{% url 'portifolio:contacts' %}">Contacts</a></li>
            </ul>
        </nav>
    </header>

    {% block content %}{% endblock %}
    
    <footer>
        <div class="foot">
        <p>&copy; 2023 Michaelmsita. All rights reserved.</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"
    integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $("#menu-icon").click(function () {
                $("nav ul").toggleClass("show");
            });
        });
    </script>

</body>

</html>

portifolio/templates/portifolio/contacts.html
{% extends 'portifolio/base.html' %}
{% load static %}
{% block title %}Contacts{% endblock %}
{% block content %}

<h1 class="services-style"><b>Contact Me</b></h1>
<p class="services-style">
    Feel free to get in touch with me if you have any questions, or you'd like to discuss a potential project. I'm always here to assist you.
</p>

<h1 class="services-style"> <b>Contact Information</b></h1>
<ul class="services-style">
    <li><b>Email:</b><a href="mailto:michaelmsita17@gmail.com">Gmail Me</a></li>
    <li><b>Phone:</b><a href="tel:+255612350807">+255612350807</a></li>
    <li><b>Location:</b> Dar-es-salaam, Tanzania</li>
    <li><b>Social Media:</b> You can also connect with me on <a href="http://github.com/Michy010">Github</a>, <a href="http://Twitter.com/Fine Tech"> Twitter</a>, </li>

</ul>

<h1 class="services-style">Business Hours</h1>
<p class="services-style">
    I'm generally available during these hours:
    <ul class="services-style">
        <li>Monday to Friday: 5:00 PM - 8:00 PM</li>
        <li>Weekends: 8:00 AM - 8:00 PM</li>
    </ul>
    <P class="services-style">
        Please note that responsible times may vary, but I strive to reply to all inquiries promptly.
    </P>
</p>
{% endblock %}

portifolio/templates/portifolio/home.html
{% extends 'portifolio/base.html' %}
{% block title %}Home - Msita-portifolio{% endblock %}
{% load static %}

{% block content %}
    <section id="welcome">
        <img src="{% static 'portifolio/img/welcome.jpg' %}" alt="Welcome Image">
        <h2>Welcome to My Portfolio!</h2>
        <p>Explore my journey in environmental health, technology, and graphics. Feel free to connect with me!</p>
        <div class="social-icons">
            <a href="https://www.linkedin.com/in/michael-msita-3a64b1292/" target="_blank"><i class="fab fa-linkedin"></i>linkedin</a>
            <a href="https://github.com/Michy010" target="_blank"><i class="fab fa-github"></i>github</a>
        </div>
    </section>

{% endblock %}

portifolio/templates/portifolio/index.html
{% extends 'portifolio/base.html' %}
{% block title %}Home - Msita-portifolio{% endblock %}
{% load static %}

{% block content %}
    <section id="welcome">
        <img src="{% static 'portifolio/img/welcome.jpg' %}" alt="Welcome Image">
        <h2>Welcome to My Portfolio!</h2>
        <p>Explore my journey in environmental health, technology, and graphics. Feel free to connect with me!</p>
        <div class="social-icons">
            <a href="https://www.linkedin.com/in/michael-msita-3a64b1292/" target="_blank"><i class="fab fa-linkedin"></i>linkedin</a>
            <a href="https://github.com/Michy010" target="_blank"><i class="fab fa-github"></i>github</a>
        </div>
    </section>

{% endblock %}

portifolio/templates/portifolio/potifolio.html
{% extends 'portifolio/base.html' %}
{% load static %}
{% block title %}portfolios{% endblock %}
{% block content %}

<div class="portfolio-container">
    {% for project in projects %}
    <div class="project-div">
        <div><h2>{{ project.title }}</h2></div>
        <div>{{ project.description }}</div>
        <div class="project-image"><img src="{{project.image.url}}" alt="{{project.title}} image"></div>
        <div>Technologies Used: {{ project.technologies_used }}</div>
        <a href="{{ project.website_link }}" target="_blank"><b>View Project</b></a>
    </div>
    {% empty %}
    <p>No projects in the portfolio yet.</p>
    {% endfor %}
</div>
{% endblock %}

portifolio/templates/portifolio/services.html
{% extends 'portifolio/base.html' %}
{% load static %}
{% block title %}services{% endblock %}
{% block content %}

<h1 class="services-style"><b>SERVICES</b></h1>
<p class="services-style">
    As a software developer, I offer a range of services to help you establish a strong online presence and achieve your goals. I combine my skills in software development with a deep understanding of the latest technologies to deliver high-quality solutions tailored to your needs.
</p>

<div class="services-flexbox-container">
    <div class="django-webapp-div">
        <div class="django-app-badge">1</div>
        <div class="django-app-image"><img src="{% static 'portifolio/img/Django.PNG' %}" alt="django-app-icon"></div>
        <div class="django-app-paragraph">
            <p>Develop secure, scalable web applications tailored to your business using Django </p>
        </div>
    </div>


    <div class="django-webapp-div">
        <div class="django-app-badge">2</div>
        <div class="django-app-image"><img src="{% static 'portifolio/img/SEO.PNG' %}" alt="django-app-icon"></div>
        <div class="django-app-paragraph">
            <p>Enhence your website visibility and drive organic traffic with our expert SEO services</p>
        </div>
    </div>


    <div class="django-webapp-div">
        <div class="django-app-badge">3</div>
        <div class="django-app-image"><img src="{% static 'portifolio/img/Graphics_design.JPG' %}" alt="django-app-icon"></div>
        <div class="django-app-paragraph">
            <p>Create captivating logos, branding, and design to visually engage your audience</p>
        </div>
    </div>
</div>

<!-- <p class="services-style">
    <b>1. Website Design and development</b>
        <ul class="services-style">
            <li>Create modern and responsive websites that are visually appealing and user-friendly.</li>
            <li>Develop custom websites from scratch, ensuring a unique online identity for your brand.</li>
        </ul>
</p>

<p class="services-style">
    <b>2. E-Commerce solutions</b>
        <ul class="services-style">
            <li>Build secure and efficient online stores with payment gateway integration.</li>
            <li>Implement inventory management and product catalog systems to streamline your online sales.</li>
        </ul>
</p>

<p class="services-style">
    <b>3. Content Management System (CMS)</b>
        <ul class="services-style">
            <li>Set up and customize CMS platforms like WordPress, making it easy for you to manage your website's content.</li>
        </ul>
</p>

<p class="services-style">
    <b>4. Mobile-friendlyy Design </b>
        <ul class="services-style">
            <li>Optimize your website for mobile devices to reach a broader audience.</li>
            <li>Ensure seamless navigation and performance on smartphones and tablets.</li>
        </ul>
</p>

<p class="services-style">
    <b>5. Website Maintainance and Support </b>
        <ul class="services-style">
            <li>Providing ongoing support to keep your website running smoothly.</li>
            <li>Perform updates, security checks, and troubleshooting as needed</li>
        </ul>
</p>

<p class="services-style">
    <b>6. SEO and Digital Marketing integration </b>
        <ul class="services-style">
            <li>Enhence your website visibility in search engines</li>
            <li>Intergrate SEO best practices and digital Marketing tools for improved online reach</li>
        </ul>
</p>

<p class="services-style">
    <b>7. Custom Web Applications </b>
        <ul class="services-style">
            <li>Develop web based applications tailoored to your specific business needs.</li>
            <li>Ensure robust functionality and scalability.</li>
        </ul>
</p> -->
{% endblock %}
<script src="script.js"></script>